# Generated by Django 5.1.3 on 2025-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='tipo',
            field=models.CharField(choices=[('aliado', 'Aliado'), ('inimigo', 'Inimigo')], max_length=7),
        ),
    ]
