# Generated by Django 5.1.3 on 2025-02-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0002_alter_personagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='tipo',
            field=models.CharField(choices=[('ALIADO', 'Aliado'), ('INIMIGO', 'Inimigo')], max_length=7),
        ),
    ]
