# Generated by Django 5.1.3 on 2025-02-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0003_alter_personagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='agilidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='armadura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='defesa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='forca',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='magia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='pv',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='resistencia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='sorte',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
